version: "3.8"

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: snapp-alpine
        container_name: snapp-panel
        restart: unless-stopped
        working_dir: /var/www/html
        tty: true
        ports:
            - "8080:8080"
        volumes:
            - ./:/var/www/html
        networks:
            - snapp-ag
    db:
      image: mysql:9
      container_name: snapp-db
      environment:
        - MYSQL_ROOT_PASSWORD=1234567
        - MYSQL_PASSWORD=123456
        - MYSQL_DATABASE=snapp_db
        - MYSQL_USER=snapp_db_user
      volumes:
        - snapp_db_data:/var/lib/mysql
        - .docker/dev/config/mysqlconf:/etc/mysql/conf.d
      networks:
        - snapp-ag

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - db
      environment:
        - PMA_HOST=db
        - UPLOAD_LIMIT=64M
      restart: unless-stopped
      ports:
        - "8061:80"
      networks:
        - snapp-ag

#    redis:
#        image: redis:alpine
#        container_name: snapp-redis
#        hostname: redis
#        networks:
#            - snapp-ag
#        healthcheck:
#            test: [ "CMD", "redis-cli", "ping" ]
#            retries: 3
#            timeout: 5s

networks:
    snapp-ag:

volumes:
  snapp_db_data:

